//
// Created by user on 01.03.2022.
//

#ifndef COURSE_REMOVEADJACENTEQUALLETTERS_H
#define COURSE_REMOVEADJACENTEQUALLETTERS_H

//
void removeAdjacentEqualLetters(char *s);

#endif //COURSE_REMOVEADJACENTEQUALLETTERS_H
